# Generated by Django 4.1.4 on 2023-06-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPortalApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
